// Generated by gencpp from file service_pkg/addition.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_ADDITION_H
#define SERVICE_PKG_MESSAGE_ADDITION_H

#include <ros/service_traits.h>


#include <service_pkg/additionRequest.h>
#include <service_pkg/additionResponse.h>


namespace service_pkg
{

struct addition
{

typedef additionRequest Request;
typedef additionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addition
} // namespace service_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_pkg::addition > {
  static const char* value()
  {
    return "2e826885481512e423cbb9c656d021d7";
  }

  static const char* value(const ::service_pkg::addition&) { return value(); }
};

template<>
struct DataType< ::service_pkg::addition > {
  static const char* value()
  {
    return "service_pkg/addition";
  }

  static const char* value(const ::service_pkg::addition&) { return value(); }
};


// service_traits::MD5Sum< ::service_pkg::additionRequest> should match
// service_traits::MD5Sum< ::service_pkg::addition >
template<>
struct MD5Sum< ::service_pkg::additionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::addition >::value();
  }
  static const char* value(const ::service_pkg::additionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::additionRequest> should match
// service_traits::DataType< ::service_pkg::addition >
template<>
struct DataType< ::service_pkg::additionRequest>
{
  static const char* value()
  {
    return DataType< ::service_pkg::addition >::value();
  }
  static const char* value(const ::service_pkg::additionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_pkg::additionResponse> should match
// service_traits::MD5Sum< ::service_pkg::addition >
template<>
struct MD5Sum< ::service_pkg::additionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::addition >::value();
  }
  static const char* value(const ::service_pkg::additionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::additionResponse> should match
// service_traits::DataType< ::service_pkg::addition >
template<>
struct DataType< ::service_pkg::additionResponse>
{
  static const char* value()
  {
    return DataType< ::service_pkg::addition >::value();
  }
  static const char* value(const ::service_pkg::additionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_ADDITION_H
