// Generated by gencpp from file service_pkg/velocity.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_VELOCITY_H
#define SERVICE_PKG_MESSAGE_VELOCITY_H

#include <ros/service_traits.h>


#include <service_pkg/velocityRequest.h>
#include <service_pkg/velocityResponse.h>


namespace service_pkg
{

struct velocity
{

typedef velocityRequest Request;
typedef velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct velocity
} // namespace service_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_pkg::velocity > {
  static const char* value()
  {
    return "24d4aa458d7e3c3fb301764dff85bbff";
  }

  static const char* value(const ::service_pkg::velocity&) { return value(); }
};

template<>
struct DataType< ::service_pkg::velocity > {
  static const char* value()
  {
    return "service_pkg/velocity";
  }

  static const char* value(const ::service_pkg::velocity&) { return value(); }
};


// service_traits::MD5Sum< ::service_pkg::velocityRequest> should match
// service_traits::MD5Sum< ::service_pkg::velocity >
template<>
struct MD5Sum< ::service_pkg::velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::velocity >::value();
  }
  static const char* value(const ::service_pkg::velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::velocityRequest> should match
// service_traits::DataType< ::service_pkg::velocity >
template<>
struct DataType< ::service_pkg::velocityRequest>
{
  static const char* value()
  {
    return DataType< ::service_pkg::velocity >::value();
  }
  static const char* value(const ::service_pkg::velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_pkg::velocityResponse> should match
// service_traits::MD5Sum< ::service_pkg::velocity >
template<>
struct MD5Sum< ::service_pkg::velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::velocity >::value();
  }
  static const char* value(const ::service_pkg::velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::velocityResponse> should match
// service_traits::DataType< ::service_pkg::velocity >
template<>
struct DataType< ::service_pkg::velocityResponse>
{
  static const char* value()
  {
    return DataType< ::service_pkg::velocity >::value();
  }
  static const char* value(const ::service_pkg::velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_VELOCITY_H
