// Generated by gencpp from file service_pkg/velocityRequest.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_VELOCITYREQUEST_H
#define SERVICE_PKG_MESSAGE_VELOCITYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_pkg
{
template <class ContainerAllocator>
struct velocityRequest_
{
  typedef velocityRequest_<ContainerAllocator> Type;

  velocityRequest_()
    : vel(0.0)
    , angle(0.0)  {
    }
  velocityRequest_(const ContainerAllocator& _alloc)
    : vel(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _vel_type;
  _vel_type vel;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::service_pkg::velocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_pkg::velocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct velocityRequest_

typedef ::service_pkg::velocityRequest_<std::allocator<void> > velocityRequest;

typedef boost::shared_ptr< ::service_pkg::velocityRequest > velocityRequestPtr;
typedef boost::shared_ptr< ::service_pkg::velocityRequest const> velocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_pkg::velocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_pkg::velocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_pkg::velocityRequest_<ContainerAllocator1> & lhs, const ::service_pkg::velocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vel == rhs.vel &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_pkg::velocityRequest_<ContainerAllocator1> & lhs, const ::service_pkg::velocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_pkg::velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::velocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::velocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_pkg::velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56b3c950fbe3e7dc9e7434c86bc55fdc";
  }

  static const char* value(const ::service_pkg::velocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56b3c950fbe3e7dcULL;
  static const uint64_t static_value2 = 0x9e7434c86bc55fdcULL;
};

template<class ContainerAllocator>
struct DataType< ::service_pkg::velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_pkg/velocityRequest";
  }

  static const char* value(const ::service_pkg::velocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_pkg::velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vel\n"
"float32 angle\n"
;
  }

  static const char* value(const ::service_pkg::velocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_pkg::velocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_pkg::velocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_pkg::velocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_VELOCITYREQUEST_H
